name: rinha-2026

x-api: &api-template
  image: ghcr.io/bertbr/rinha-2026-api:go-r2
  pull_policy: always
  restart: unless-stopped
  volumes:
    - sockets:/sockets
  ulimits:
    nofile:
      soft: 65536
      hard: 65536

services:
  api1:
    <<: *api-template
    container_name: rinha-api1
    environment:
      UDS_PATH: /sockets/api1.sock
      GOMAXPROCS: "2"
      GOGC: "200"
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160MB"

  api2:
    <<: *api-template
    container_name: rinha-api2
    environment:
      UDS_PATH: /sockets/api2.sock
      GOMAXPROCS: "2"
      GOGC: "200"
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160MB"

  lb:
    image: haproxy:3.0-alpine
    container_name: rinha-lb
    restart: unless-stopped
    depends_on:
      - api1
      - api2
    volumes:
      - sockets:/sockets
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "30MB"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  sockets:

networks:
  default:
    driver: bridge
