name: rinha-2026

x-api: &api-template
  image: ghcr.io/bertbr/rinha-2026-api:go-r9
  pull_policy: always
  restart: unless-stopped
  volumes:
    - sockets:/sockets
  ulimits:
    nofile:
      soft: 65536
      hard: 65536

services:
  api1:
    <<: *api-template
    container_name: rinha-api1
    environment:
      CTRL_SOCKET: /sockets/api1.ctrl
      GOMAXPROCS: "2"
      GOGC: "200"
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160MB"

  api2:
    <<: *api-template
    container_name: rinha-api2
    environment:
      CTRL_SOCKET: /sockets/api2.ctrl
      GOMAXPROCS: "2"
      GOGC: "200"
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160MB"

  lb:
    image: ghcr.io/bertbr/rinha-2026-lb:go-r1
    pull_policy: always
    container_name: rinha-lb
    restart: unless-stopped
    depends_on:
      - api1
      - api2
    command:
      - "-listen=:9999"
      - "-workers=/sockets/api1.ctrl,/sockets/api2.ctrl"
    volumes:
      - sockets:/sockets
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "30MB"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  sockets:

networks:
  default:
    driver: bridge
