name: rinha-2026

x-api: &api-template
  image: ghcr.io/bertbr/rinha-2026-api:vpt3-r1
  pull_policy: always
  restart: unless-stopped
  volumes:
    - sockets:/sockets
  ulimits:
    nofile:
      soft: 65536
      hard: 65536

services:
  api1:
    <<: *api-template
    container_name: rinha-api1
    environment:
      UDS_PATH: /sockets/api1.sock
      WARMUP_QUERIES: 3000
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "165MB"

  api2:
    <<: *api-template
    container_name: rinha-api2
    environment:
      UDS_PATH: /sockets/api2.sock
      WARMUP_QUERIES: 3000
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "165MB"

  lb:
    image: haproxy:3.0-alpine
    container_name: rinha-lb
    restart: unless-stopped
    depends_on:
      - api1
      - api2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20MB"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  sockets:

networks:
  default:
    driver: bridge
